language: objective-c

osx_image: xcode7.3

before_install:
  - brew update
  - brew outdated carthage || brew update carthage
before_script:
  - carthage bootstrap
script: xcodebuild -scheme "GuardedSwiftyJson" -destination "platform=iOS Simulator,name=iPhone 6" test
